# Generated by Django 5.2.11 on 2026-03-05 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0002_oauthapplication_profile_oauthapplication_project_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorizationcode',
            name='code_challenge',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='authorizationcode',
            name='code_challenge_method',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
